[project]
name = "Asteroids -- easy and lazy version"
version = "1.0.0"
description = "Created as a Boot.dev project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
